lab_1/urls.py
from django.urls import path
from .views import index, friend_list

urlpatterns = [
    path('', index, name='index'),
    path('friends', friend_list, name='friend_list')
    # TODO Add friends path using friend_list Views
]

lab_2/urls.py
from django.urls import path
from .views import index, xml, json

urlpatterns = [
    path('', index, name='index'),
    path('xml/', xml, name='xml'),
    path('json/', json, name='json')
]

lab_3/urls.py
from django.urls import path
from .views import add_friend, index

app_name = "lab_3"

urlpatterns = [
    path('', index, name='index'),
    path('add/', add_friend, name='add_friend'),
]

lab_4/urls.py
from django.urls import path
from .views import index, add_note, note_list

app_name = "lab_4"

urlpatterns = [
    path('', index, name='index'),
    path('add-note/', add_note, name='add-note'),
    path('note-list/', note_list, name='note-list'),
]

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include(lab_1)),
    path('lab-2/', include(lab_2)),
    path('lab-3/', include(lab_3)),
    path('lab-4/', include(lab_4)),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here


class Friend(models.Model):
    name = models.CharField(max_length=30)
    npm = models.CharField(max_length=10)
    dob = models.DateField()
    # TODO Implement missing attributes in Friend model

lab_2/models.py
from django.db import models

# Create Note model that contains to, from, title, and message.

class Note(models.Model):
    untuk = models.CharField(max_length=100)
    dari = models.CharField(max_length=100)
    judul = models.CharField(max_length=500)
    pesan = models.TextField()

lab_4/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django.forms import ModelForm
from lab_1.models import Friend

class FriendForm(ModelForm):
    class Meta:
        model = Friend
        fields = ["name","npm","dob"]

lab_4/forms.py
from django.forms import ModelForm
from lab_2.models import Note
from django.forms.widgets import Input


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ["untuk", "dari", "judul", "pesan"]
        widgets = {
            "untuk": Input(attrs={"class": "form-control"}),
            "dari": Input(attrs={"class": "form-control"}),
            "judul": Input(attrs={"class": "form-control"}),
            "pesan": Input(attrs={"class": "form-control"})
        }

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = 'Jenny'  # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 9, 16)  # TODO Implement this, format (Year, Month, Date)
npm = 2006596516  # TODO Implement this


def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)


def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0


def friend_list(request):
    friends = Friend.objects.all()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from .models import Note
from django.http.response import HttpResponse
from django.core import serializers

# Create your views here.

def index(request):
    notes = Note.objects.all() 
    response = {'notes': notes}
    return render(request, 'lab2.html', response)

def xml(request):
    notes = Note.objects.all() 
    data = serializers.serialize('xml', notes)
    return HttpResponse(data, content_type="application/xml")

def json(request):
    notes = Note.objects.all() 
    data = serializers.serialize('json', notes)
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.shortcuts import redirect, render
from lab_1.models import Friend
from lab_3.forms import FriendForm
from django.contrib.auth.decorators import login_required

def index(request):
    friends = Friend.objects.all()  # TODO Implement this
    response = {'friends': friends}
    return render(request, 'lab3_index.html', response)

@login_required(login_url="/admin/login/")
def add_friend(request):
    if request.method == "POST":
        form = FriendForm(request.POST)
        if form.is_valid():
            form.save() 
            return redirect("lab_3:index")
        print(form.errors)
    form = FriendForm()
    context = {"form" : form}
    return render(request, "lab3_form.html", context)

lab_4/views.py
from django.http import request
from django.shortcuts import render, redirect
from lab_2.models import Note
from lab_4.forms import NoteForm
# Create your views here.

def index(request):
    notes = Note.objects.all() 
    response = {'notes': notes}
    return render(request, 'lab4_index.html', response)

def add_note(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save() 
            return redirect("lab_4:index")
    form = NoteForm()
    context = {"form" : form}
    return render(request, "lab4_form.html", context)

def note_list(request):
    notes = Note.objects.all() 
    response = {'notes': notes}
    return render(request, 'lab4_note_list.html', response)

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table>
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      
      {% for friend in friends %}
      <tr>
        <td>{{friend.name}}</td>
        <td>{{friend.npm}}</td>
        <td>{{friend.dob}}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body bgcolor="black">
    <div align="center">
    <h1 style="color: white;">Hello my name is {{ name }}</h1>
    <article style="color: white;">NPM : {{ npm }}</article>
    <article style="color: white;">I am {{ age }} years old</article>
    <br>
    <img src="https://i.redd.it/gh90i7i1pk531.jpg"  width="500" height="600">
  </div>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lab 2</title>
    <h1 style="font-size: xx-large;" align="center">💌 List of Messages 💌</h1>
</head>
<body bgcolor="ffeee8">
    <table align="center" style="width: 50%;" border="1 px">
        <tr style="background-color: #C08F73;">
          <th style="width: 12.5%;">To</th>
          <th style="width: 12.5%;">From</th>
          <th style="width: 25%;">Title</th>
          <th style="width: 50%;">Messages</th>
        </tr>
        
        {% for note in notes %}
        <tr style="background-color: #E8CAB3;">
          <td>{{note.untuk}}</td>
          <td>{{note.dari}}</td>
          <td>{{note.judul}}</td>
          <td>{{note.pesan}}</td>
        </tr>
        {% endfor %}
</body>
</html>

lab_3/templates/lab3_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Friend</title>
</head>

<body>
    <header>
        <h1>Add Friend</h1>
    </header>
    <section>
        <form action="" method="POST">
            {% csrf_token %}
            <div>
                <label for="name">Name</label>
                {{ form.name }}
            </div>
            <div>
                <label for="npm">npm</label>
                {{ form.npm }}
            </div>
            <div>
                <label for="dob">Date of Birth</label>
                {{ form.dob }}
            </div>
            <button>Add Friend</button>
        </form>
    </section>
</body>

</html>

lab_3/templates/lab3_index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <title>Friend List</title>
</head>

<body bgcolor="ffeee8">
  <h1 style="font-size: xx-large;" align="center">Friend List ヾ(•ω•`)o</h1>
  <table align="center" style="width: 50%;" border="1 px">
    <tr style="background-color: #C08F73;">
      <th style="width: 33.3%;">Name</th>
      <th style="width: 33.3%;">NPM</th>
      <th style="width: 33.3%;">DOB</th>
    </tr>

    {% for friend in friends %}
    <tr style="background-color: #E8CAB3;">
      <td>{{friend.name}}</td>
      <td>{{friend.npm}}</td>
      <td>{{friend.dob}}</td>
    </tr>
    {% endfor %}
  </table>
  <br>
  <div align="center">
  <a href="{% url 'lab_3:add_friend' %}">
    <button>
      Add Friend
    </button>
  </a>
  </div>
</body>
</html>

lab_4/templates/lab4_base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>Lab 4</title>
</head>

<body>
  <!-- Navbar -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'lab_4:index' %}">Lab 4</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'lab_4:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab_4:add-note' %}">Add Note</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab_4:note-list' %}">Note List</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- End of Navbar -->

  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>


  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

lab_4/templates/lab4_form.html
{% extends 'lab4_base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center mb-5">Write Your Note! 📝</h1>

<div class="d-flex align-items-center flex-lg-row flex-column-reverse">

    <form action="" method="post" class="col-8">
        {% csrf_token %}
        <div class="mb-3">
            <label for="untuk" class="form-label">To :</label>
            {{ form.untuk }}
        </div>
        <div class="mb-3">
            <label for="dari" class="form-label">From :</label>
            {{ form.dari }}
        </div>
        <div class="mb-3">
            <label for="judul" class="form-label">Title :</label>
            {{ form.judul }}
        </div>
        <div class="mb-3">
            <label for="pesan" class="form-label">Messages :</label>
            {{ form.pesan }}
        </div>
        <button type="submit" class="btn btn-primary border-0 fw-bold" style="background-color: #FEDB2C; color: #3A1C03;" >Submit</button>
    </form>
    <div class="col-4 d-flex justify-content-center align-items-center">
        <img src="{% static 'lab_4/pika.png' %}" alt="pikachu">
    </div>
</div>



{% endblock content %}

lab_4/templates/lab4_index.html
{% extends 'lab4_base.html' %}

{% block content %}
<h1 class="text-center mb-5">List of Messages 💌</h1>

<div class="border rounded border-bottom-0">
  <table class="table table-striped">
    <thead style="background-color: #FEDB2C;">
      <tr style="color: #3A1C03;">
        <th scope="col">No</th>
        <th scope="col">To</th>
        <th scope="col">From</th>
        <th scope="col">Title</th>
        <th scope="col">Messages</th>
      </tr>
    </thead>
    <tbody>
      {% for note in notes %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{note.untuk}}</td>
        <td>{{note.dari}}</td>
        <td>{{note.judul}}</td>
        <td>{{note.pesan}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

lab_4/templates/lab4_note_list.html
{% extends 'lab4_base.html' %}
{% load static %}

{% block content %}
<h1 class="text-center mb-5">Note Lists 📬</h1>

<div class="d-flex flex-wrap justify-content-center">
    {% for notes in notes %}
    <div class="col-12 col-lg-5 card mb-3 shadow rounded-3 d-flex flex-row mx-2">
        <div class="p-4" style="background-color: #FEDB2C;width: 35%;">
            <h6 style="color: #3A1C03;" class="fw-bold text">From: {{notes.dari}}</h6>
            <h6 style="color: #3A1C03;" class="fw-bold">To: {{notes.untuk}}</h6>
        </div>
        <div style="width: 65%;" class="p-4">
            <h5> {{notes.judul}} </h5>
            <p>"{{notes.pesan}}"</p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}